---
output:
    rmdformats::material:
        use_bookdown: true
        thumbnails: false
        df_print: kable
        code_folding: hide
        number_sections: yes
---

# Metadata

## Parameters
```{r show-params}
library(kableExtra)

ul <- unlist(parameters_list)
df <- data.frame(keyName=names(ul), value=ul, row.names=NULL)
names(df) <- c('Parameters', 'Values')

# découpage du dataframe df en 3 pour générer 3 colonnes à l'affichage
df1 <- df[1:ceiling(dim(df)[1]/3),]
df2 <- df[(ceiling(dim(df)[1]/3)+1):(2*ceiling(dim(df)[1]/3)),]
df3 <- df[((2*ceiling(dim(df)[1]/3))+1):dim(df)[1],]

# make the Parameters being bold
df1$Parameters <- cell_spec(df1$Parameters, bold = T)
df2$Parameters <- cell_spec(df2$Parameters, bold = T)
df3$Parameters <- cell_spec(df3$Parameters, bold = T)

# combine the dataframes into a single table
list(df1, df2, df3) %>%
  knitr::kable(align = "ll", row.names = FALSE, escape = F) %>% 
  kable_styling(bootstrap_options = c("striped", "hover"),
                full_width = FALSE)
```

## R Session Info

```{r sessionInfo}
sessionInfo()
```