# Welcome to the config file relative to a dataset

# WARNING: the title must contain the name of the DATASET as defined in the
# file.


# ===================
# required parameters
# ===================
DATASET = "MODEL"
CONDITION = ["condition1", "conditionA"]


# general parameters
general_seed = 17

# analysis gene reference
GENE_NAME_COLUMN = 1			# 1 or 2 (see raw data features file)

# scenario to select from the step dea
REGRESSION_SCENARIO = [1]	# list of scenario(s): 1 or 2 or 3 or any combination

[path]
PATH_ROOT = "XXXXX"

[path.input]
PATH_INPUT_LABDATA = "XXXXX"
PATH_ATLAS = "XXXXX"
PATH_ATLAS_FILE = "XXXXX"
# optional params
PATH_GENES_OF_INTEREST = "XXXXX"		# path from the PATH_ROOT to the list of genes of interest

[path.output]
PATH_RDS_OBJECTS	= "50_rdsObjects"	# create path PATH_ROOT/PATH_RDS_OBJECTS
PATH_OUT_HTML		= "51_htmlFiles"	# create path PATH_ROOT/PATH_OUT_HTML
PATH_OUT_FIG		= "52_figures"		# create path PATH_ROOT/PATH_OUT_FIG/DATASET



# ===================
# optional parameters
# ===================
[qc]
MITO_HIGH = 25					# integers ranging from 0 to 100
MITO_LOW = 1					# integers ranging from 0 to 100
RIBO_LOW = 8					# integers ranging from 0 to 100
MIN_COUNTS = 500
MAX_COUNTS = 60000
MIN_FEAT = 200
MIN_CELLS = 3

[process]
NORM_METH = "LogNormalize"			# LogNormalize or SCTransform
HVG_METH = "mvp"					# mvp, vst or disp
HVG_NUM = false						# mvp doesn't need HVG_NUM, vst and disp does	
DO_SCALE = false
PCA_NPCS = 50
PCA_PRINT = 20
TOP_PCS = 30
CLUST_RES = 1.0
CLUST_METH = 4					# 1: Louvain, 2: Louvain multilevel refinement, 3: SLM or 4: Leiden


# Set of parameters to explore in detail the populations of cells in the dataset
# These parameters are used when running the filters --manual pipeline
[filters]
#MITO_THRESHOLDS	= []		# list of thresholds ranging from 0.0 to 100.0
#RIBO_THRESHOLDS	= []		# list of thresholds ranging from 0.0 to 100.0
#UMI_THRESHOLDS		= []		# list of thresholds based on observations
#FEATURE_THRESHOLDS = []		# list of thresholds based on observations

[ctrl]
FILTER_FEATURES = ["XXX"]    # list of the marker genes of the celltype to remove (gene name or EnsemblID). To remove red blood cells, filter "Hba-a1"
OBSERVE_FEATURES = []   # list of the marker genes to observe and eventually remove at the post-ctrl process step 
dblt_rate = 8
S_PHASE = 0				# /!\ both parameters should be uncommented together
G2M_PHASE = 0			# Default value can stay 0 if necessary





